#!/bin/bash

echo "🚀 Netlify Deployment Guide for Bhushan Waingankar's Portfolio"
echo "=============================================================="
echo ""

echo "✅ Repository is ready for deployment!"
echo "📁 GitHub Repository: https://github.com/bhushankorg/portfolio-website"
echo ""

echo "🌐 OPTION 1: Deploy via Netlify Dashboard (Recommended)"
echo "--------------------------------------------------------"
echo "1. Go to https://app.netlify.com/"
echo "2. Click 'Add new site' → 'Import an existing project'"
echo "3. Choose 'Deploy with GitHub'"
echo "4. Select your repository: bhushankorg/portfolio-website"
echo "5. Configure build settings:"
echo "   - Build command: npm run build"
echo "   - Publish directory: build"
echo "   - Base directory: (leave empty)"
echo "6. Click 'Deploy site'"
echo ""

echo "⚡ OPTION 2: Deploy via Netlify CLI"
echo "-----------------------------------"
echo "Run these commands:"
echo ""
echo "# Install Netlify CLI globally"
echo "npm install -g netlify-cli"
echo ""
echo "# Login to Netlify"
echo "netlify login"
echo ""
echo "# Initialize and deploy"
echo "netlify init"
echo "netlify build"
echo "netlify deploy --prod"
echo ""

echo "🔧 Build Configuration (Already Configured)"
echo "--------------------------------------------"
echo "✅ netlify.toml created with optimal settings"
echo "✅ Build command: npm run build"
echo "✅ Publish directory: build"
echo "✅ SPA redirects configured"
echo "✅ Security headers added"
echo "✅ Cache optimization enabled"
echo ""

echo "🎯 After Deployment"
echo "-------------------"
echo "• Your site will be available at: https://[random-name].netlify.app"
echo "• You can customize the domain in Netlify dashboard"
echo "• Set up custom domain if you have one"
echo "• Enable automatic deployments (already configured)"
echo ""

echo "🔄 Automatic Deployments"
echo "------------------------"
echo "Every time you push to the main branch, Netlify will:"
echo "1. Automatically detect changes"
echo "2. Run 'npm run build'"
echo "3. Deploy the updated site"
echo "4. Send you deployment notifications"
echo ""

echo "🚨 Troubleshooting"
echo "------------------"
echo "If build fails:"
echo "• Check that 'npm run build' works locally"
echo "• Verify package.json has all dependencies"
echo "• Check build logs in Netlify dashboard"
echo ""

echo "📱 Optional: Environment Variables"
echo "----------------------------------"
echo "If you need to add environment variables:"
echo "1. Go to Site settings → Environment variables"
echo "2. Add any REACT_APP_ prefixed variables"
echo "3. Redeploy the site"
echo ""

echo "🎉 Your portfolio will be live within minutes!"
echo "Website URL will be: https://[your-site-name].netlify.app"
